# Serena MCP Configuration for HYDRA
# This file enables Serena code intelligence

project:
  name: "HYDRA"
  version: "10.6.1"
  type: "typescript"

analysis:
  enabled: true
  languages:
    - typescript
    - javascript
    - rust
    - python

symbols:
  index: true
  max_depth: 10

features:
  code_navigation: true
  references: true
  definitions: true
  hover_info: true
